name: Deploy master
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: AKIASQQZGYJS2VSZWW43
          aws_secret_key: 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
          application_name: my-react-application
          environment_name: My-react-application-env-1
          version_label: ${{ github.sha}}
          existing_bucket_name: elasticbeanstalk-ap-south-1-643867272633
          region: ap-south-1
          deployment_package: deploy.zip
